// Compact emoji table: [codepoint_hex, name, keywords]
// ~300 most commonly used emoji across all major categories
const EMOJI_DATA = [
  // Smileys & Emotion
  ['1F600','grinning face','happy smile laugh'],
  ['1F601','beaming face with smiling eyes','happy grin'],
  ['1F602','face with tears of joy','laugh cry lol'],
  ['1F603','smiling face with open mouth','happy smile'],
  ['1F604','smiling face with open mouth and smiling eyes','happy grin'],
  ['1F605','grinning face with sweat','phew nervous'],
  ['1F606','grinning squinting face','laugh'],
  ['1F607','smiling face with halo','angel innocent'],
  ['1F608','smiling face with horns','devil mischief'],
  ['1F609','winking face','wink flirt'],
  ['1F60A','smiling face with smiling eyes','blush happy'],
  ['1F60B','face savoring food','yum delicious'],
  ['1F60C','relieved face','phew calm'],
  ['1F60D','smiling face with heart-eyes','love heart eyes'],
  ['1F60E','smiling face with sunglasses','cool sunglasses'],
  ['1F60F','smirking face','smug'],
  ['1F610','neutral face','neutral blank'],
  ['1F611','expressionless face','no emotion'],
  ['1F612','unamused face','unamused unimpressed'],
  ['1F613','downcast face with sweat','stressed nervous'],
  ['1F614','pensive face','sad thoughtful'],
  ['1F615','confused face','confused'],
  ['1F616','confounded face','confused frustrated'],
  ['1F617','kissing face','kiss'],
  ['1F618','face blowing a kiss','kiss heart'],
  ['1F619','kissing face with smiling eyes','kiss smile'],
  ['1F61A','kissing face with closed eyes','kiss'],
  ['1F61B','face with tongue','tongue silly'],
  ['1F61C','winking face with tongue','wink tongue silly'],
  ['1F61D','squinting face with tongue','tongue silly'],
  ['1F61E','disappointed face','sad disappointed'],
  ['1F61F','worried face','worried'],
  ['1F620','angry face','angry mad'],
  ['1F621','pouting face','angry'],
  ['1F622','crying face','cry sad'],
  ['1F623','persevering face','sad frustrated'],
  ['1F624','face with steam from nose','angry triumph'],
  ['1F625','sad but relieved face','sad worry'],
  ['1F626','frowning face with open mouth','sad'],
  ['1F627','anguished face','anguish'],
  ['1F628','fearful face','fear scared'],
  ['1F629','weary face','weary tired'],
  ['1F62A','sleepy face','sleepy tired'],
  ['1F62B','tired face','tired exhausted'],
  ['1F62C','grimacing face','grimace'],
  ['1F62D','loudly crying face','cry sob'],
  ['1F62E','face with open mouth','surprised wow'],
  ['1F62F','hushed face','surprised'],
  ['1F630','anxious face with sweat','anxious'],
  ['1F631','face screaming in fear','scream scared'],
  ['1F632','astonished face','astonished wow'],
  ['1F633','flushed face','flushed embarrassed'],
  ['1F634','sleeping face','sleep zzz'],
  ['1F635','dizzy face','dizzy'],
  ['1F636','face without mouth','silent'],
  ['1F637','face with medical mask','sick mask'],
  ['1F910','zipper-mouth face','silent zip'],
  ['1F911','money-mouth face','money rich'],
  ['1F912','face with thermometer','sick fever'],
  ['1F913','nerd face','nerd glasses'],
  ['1F914','thinking face','thinking hmm'],
  ['1F915','face with head-bandage','hurt injury'],
  ['1F916','robot','robot bot'],
  ['1F917','hugging face','hug'],
  ['1F920','cowboy hat face','cowboy'],
  ['1F921','clown face','clown joker'],
  ['1F922','nauseated face','sick nausea gross'],
  ['1F923','rolling on the floor laughing','rofl laugh'],
  ['1F924','drooling face','drool hungry'],
  ['1F925','lying face','lie pinocchio'],
  ['1F927','sneezing face','sneeze sick'],
  ['1F928','face with raised eyebrow','skeptical'],
  ['1F929','star-struck','excited wow stars'],
  ['1F92A','zany face','silly wacky'],
  ['1F92B','shushing face','shush quiet'],
  ['1F92C','face with symbols on mouth','angry swear'],
  ['1F92D','face with hand over mouth','oops giggle'],
  ['1F92E','face vomiting','vomit gross sick'],
  ['1F92F','exploding head','mind blown wow'],
  ['1F970','smiling face with hearts','love adore'],
  ['1F971','yawning face','yawn tired bored'],
  ['1F972','smiling face with tear','emotional'],
  ['1F973','partying face','party celebrate'],
  ['1F974','woozy face','drunk dizzy'],
  ['1F975','hot face','hot heat'],
  ['1F976','cold face','cold frozen'],
  ['1F978','disguised face','disguise'],
  ['1F97A','pleading face','puppy eyes begging'],
  ['1F97B','sari','clothes India'],
  ['2764','red heart','love heart'],
  ['1F9E1','orange heart','love heart orange'],
  ['1F49B','yellow heart','love heart yellow'],
  ['1F49A','green heart','love heart green'],
  ['1F499','blue heart','love heart blue'],
  ['1F49C','purple heart','love heart purple'],
  ['1F5A4','black heart','heart black dark'],
  ['1F494','broken heart','heartbreak sad'],
  ['1F495','two hearts','love couple'],
  ['1F496','sparkling heart','love sparkle'],
  ['1F4AF','hundred points','100 perfect score'],
  // People & Body
  ['1F44D','thumbs up','like ok good yes'],
  ['1F44E','thumbs down','dislike no bad'],
  ['1F44F','clapping hands','clap applause'],
  ['1F44B','waving hand','wave hello hi'],
  ['1F44C','ok hand','ok perfect good'],
  ['270C','victory hand','peace victory'],
  ['1F91E','crossed fingers','luck hope'],
  ['1F44A','oncoming fist','fist bump'],
  ['270A','raised fist','fist power'],
  ['270B','raised hand','stop high five'],
  ['1F590','raised hand with fingers splayed','hand'],
  ['1F918','sign of the horns','rock metal'],
  ['1F919','call me hand','call phone'],
  ['1F91A','raised back of hand','hand stop'],
  ['1F91B','left-facing fist','fist left'],
  ['1F91C','right-facing fist','fist right'],
  ['1F91D','handshake','handshake deal'],
  ['1F91F','love-you gesture','love you'],
  ['1F446','backhand index pointing up','up point'],
  ['1F447','backhand index pointing down','down point'],
  ['1F448','backhand index pointing left','left point'],
  ['1F449','backhand index pointing right','right point'],
  ['261D','index pointing up','point up one'],
  ['1F4AA','flexed biceps','muscle strong'],
  ['1F9B5','leg','leg'],
  ['1F9B6','foot','foot'],
  ['1F440','eyes','eyes look see'],
  ['1F441','eye','eye'],
  ['1F445','tongue','tongue lick'],
  ['1F442','ear','ear hear listen'],
  ['1F443','nose','nose smell'],
  ['1F9E0','brain','brain think smart'],
  ['1F9B7','tooth','tooth'],
  ['1F9B4','bone','bone'],
  ['1F9B3','white hair','hair old white'],
  ['1F9B2','bald','bald hair'],
  ['1F478','princess','princess girl'],
  ['1F934','prince','prince boy'],
  ['1F9B8','superhero','superhero'],
  ['1F9B9','supervillain','villain'],
  ['1F46E','police officer','police cop'],
  ['1F477','construction worker','construction worker'],
  ['1F482','guard','guard soldier'],
  ['1F575','detective','detective spy'],
  ['1F473','person wearing turban','turban'],
  ['1F472','person with skullcap','hat cap'],
  ['1F9D4','bearded person','beard'],
  ['1F9D5','person with headscarf','headscarf'],
  ['1F470','bride with veil','bride wedding'],
  ['1F935','man in tuxedo','groom wedding tuxedo'],
  ['1F930','pregnant woman','pregnant'],
  ['1F931','breast-feeding','baby feed'],
  ['1F476','baby','baby infant'],
  ['1F9D2','child','child kid'],
  ['1F466','boy','boy'],
  ['1F467','girl','girl'],
  ['1F468','man','man adult male'],
  ['1F469','woman','woman adult female'],
  ['1F9D3','older person','old elderly'],
  ['1F474','old man','old man elderly'],
  ['1F475','old woman','old woman elderly'],
  // Animals & Nature
  ['1F436','dog face','dog puppy'],
  ['1F431','cat face','cat kitty'],
  ['1F42D','mouse face','mouse'],
  ['1F439','hamster','hamster'],
  ['1F430','rabbit face','rabbit bunny'],
  ['1F98A','fox','fox'],
  ['1F43B','bear','bear'],
  ['1F43C','panda','panda'],
  ['1F428','koala','koala'],
  ['1F42F','tiger face','tiger'],
  ['1F981','lion','lion'],
  ['1F42E','cow face','cow'],
  ['1F437','pig face','pig'],
  ['1F438','frog','frog'],
  ['1F435','monkey face','monkey'],
  ['1F648','see-no-evil monkey','monkey'],
  ['1F649','hear-no-evil monkey','monkey'],
  ['1F64A','speak-no-evil monkey','monkey'],
  ['1F414','chicken','chicken'],
  ['1F427','penguin','penguin'],
  ['1F426','bird','bird'],
  ['1F424','baby chick','chick baby bird'],
  ['1F986','duck','duck'],
  ['1F985','eagle','eagle'],
  ['1F989','owl','owl'],
  ['1F987','bat','bat'],
  ['1F43A','wolf','wolf'],
  ['1F417','boar','boar pig'],
  ['1F434','horse face','horse'],
  ['1F984','unicorn','unicorn horse'],
  ['1F41D','honeybee','bee'],
  ['1F98B','butterfly','butterfly'],
  ['1F40C','snail','snail slow'],
  ['1F422','turtle','turtle slow'],
  ['1F40D','snake','snake'],
  ['1F98E','lizard','lizard'],
  ['1F989','owl','owl'],
  ['1F433','spouting whale','whale ocean'],
  ['1F42C','dolphin','dolphin'],
  ['1F420','tropical fish','fish'],
  ['1F419','octopus','octopus'],
  ['1F40B','whale','whale'],
  ['1F98C','deer','deer'],
  ['1F992','giraffe','giraffe'],
  ['1F993','zebra','zebra'],
  ['1F40F','ram','ram sheep'],
  ['1F991','squid','squid'],
  ['1F990','shrimp','shrimp'],
  ['1F980','crab','crab'],
  ['1F99E','lobster','lobster'],
  ['1F99F','mosquito','mosquito bug'],
  ['1F9A0','microbe','microbe germ'],
  ['1F33A','hibiscus','flower rose'],
  ['1F338','cherry blossom','flower pink'],
  ['1F337','tulip','flower'],
  ['1F340','four leaf clover','clover luck'],
  ['1F33B','sunflower','flower sun'],
  ['1F332','evergreen tree','tree pine'],
  ['1F333','deciduous tree','tree'],
  ['1F334','palm tree','tree tropical'],
  ['1F335','cactus','cactus desert'],
  ['1F343','leaf fluttering in wind','leaf wind'],
  ['2600','sun','sun sunny'],
  ['1F31D','full moon','moon'],
  ['2B50','star','star'],
  ['1F308','rainbow','rainbow color'],
  ['2601','cloud','cloud'],
  ['26C5','sun behind cloud','partly cloudy'],
  ['1F327','cloud with rain','rain'],
  ['26A1','lightning','lightning thunder'],
  ['2744','snowflake','snow cold'],
  ['1F321','thermometer','temperature'],
  ['1F525','fire','fire hot'],
  ['1F4A7','droplet','water drop'],
  ['1F30A','water wave','ocean wave'],
  // Food & Drink
  ['1F34E','red apple','apple fruit'],
  ['1F34B','lemon','lemon citrus sour'],
  ['1F347','grapes','grapes fruit'],
  ['1F353','strawberry','strawberry fruit'],
  ['1F355','pizza','pizza food'],
  ['1F354','hamburger','burger food'],
  ['1F35F','french fries','fries food'],
  ['1F357','poultry leg','chicken food'],
  ['1F356','meat on bone','meat food'],
  ['1F35C','steaming bowl','ramen noodles'],
  ['1F363','sushi','sushi food'],
  ['1F370','shortcake','cake dessert'],
  ['1F382','birthday cake','cake birthday'],
  ['1F36B','chocolate bar','chocolate candy'],
  ['1F4A9','pile of poo','poop'],
  ['1F37B','clinking beer mugs','beer cheers'],
  ['1F37A','beer mug','beer'],
  ['1F377','wine glass','wine'],
  ['1F378','cocktail glass','cocktail drink'],
  ['2615','hot beverage','coffee tea'],
  ['1F376','sake','sake japan'],
  ['1F375','teacup without handle','tea cup'],
  ['1F37E','bottle with popping cork','champagne'],
  ['1F942','clinking glasses','cheers toast'],
  ['1F943','tumbler glass','whiskey drink'],
  ['1F964','cup with straw','drink juice'],
  ['1F9C3','beverage box','juice drink'],
  ['1F9C9','mate','drink'],
  ['1F9CA','ice','ice cube cold'],
  // Activities & Sports
  ['26BD','soccer ball','soccer football'],
  ['1F3C0','basketball','basketball'],
  ['1F3C8','american football','football'],
  ['26BE','baseball','baseball'],
  ['1F3BE','tennis','tennis'],
  ['1F3D0','volleyball','volleyball'],
  ['1F3C6','trophy','trophy win'],
  ['1F947','1st place medal','gold medal win'],
  ['1F3C3','running','run exercise'],
  ['1F3CA','swimming','swim'],
  ['1F3CB','lifting weights','gym weights'],
  ['1F6B4','bicyclist','cycling bike'],
  ['26F7','skier','ski snow'],
  ['1F3C4','surfer','surf wave'],
  ['1F3A4','microphone','mic sing'],
  ['1F3A8','artist palette','art paint'],
  ['1F3B8','guitar','guitar music'],
  ['1F3B9','musical keyboard','piano music'],
  ['1F3BA','trumpet','trumpet music'],
  ['1F3BB','violin','violin music'],
  ['1F941','drum','drum music'],
  ['1F3B2','game die','dice game'],
  ['265F','chess pawn','chess game'],
  ['1F3AE','video game','game controller'],
  ['1F3B0','slot machine','slot game'],
  // Travel & Places
  ['1F697','automobile','car drive'],
  ['1F695','taxi','taxi cab'],
  ['1F68C','bus','bus transport'],
  ['1F682','locomotive','train'],
  ['2708','airplane','plane fly'],
  ['1F680','rocket','rocket space'],
  ['1F6F8','flying saucer','ufo alien'],
  ['1F6F3','passenger ship','ship boat'],
  ['26F5','sailboat','boat sail'],
  ['1F3E0','house','home house'],
  ['1F3E2','office building','building office'],
  ['1F3E5','hospital','hospital medical'],
  ['1F3E6','bank','bank money'],
  ['1F3EB','school','school education'],
  ['1F3EC','department store','shopping store'],
  ['1F5FD','statue of liberty','statue liberty'],
  ['1F5FC','tokyo tower','tower japan'],
  ['1F30D','globe showing Europe-Africa','world globe earth'],
  ['1F30E','globe showing Americas','world globe'],
  ['1F30F','globe showing Asia-Australia','world globe'],
  ['1F5FA','world map','map world'],
  ['1F5FF','moyai','moai easter island'],
  // Objects
  ['1F4F1','mobile phone','phone mobile'],
  ['1F4BB','laptop','laptop computer'],
  ['1F4BA','seat','chair seat'],
  ['1F4DA','books','books read'],
  ['1F4D6','open book','book read'],
  ['1F4DD','memo','note write'],
  ['1F4CE','paperclip','paperclip attach'],
  ['1F4CC','pushpin','pin location'],
  ['1F4CD','round pushpin','pin location'],
  ['2702','scissors','scissors cut'],
  ['1F527','wrench','wrench tool fix'],
  ['1F528','hammer','hammer tool'],
  ['1F52E','crystal ball','magic fortune'],
  ['1F52D','telescope','telescope space science'],
  ['1F4A1','light bulb','idea light'],
  ['1F526','flashlight','flashlight torch'],
  ['1F4B0','money bag','money rich'],
  ['1F4B5','dollar banknote','money dollar'],
  ['1F4B8','money with wings','money fly'],
  ['1F3E7','atm sign','atm cash'],
  ['1F4B1','currency exchange','exchange money'],
  ['1F4B2','heavy dollar sign','dollar money'],
  ['1F4B3','credit card','card credit bank'],
  ['1F48E','gem stone','diamond gem'],
  ['1F48D','ring','ring wedding'],
  ['1F451','crown','crown king queen'],
  ['1F452','woman hat','hat fashion'],
  ['1F9E2','billed cap','cap hat'],
  ['1F393','graduation cap','graduation school'],
  ['1F3A9','top hat','hat fancy'],
  ['1F9E3','scarf','scarf winter'],
  ['1F9E4','gloves','gloves winter'],
  ['1F9E5','coat','coat fashion'],
  ['1F9E6','socks','socks'],
  ['1F461','womans sandal','shoe'],
  ['1F462','womans boots','boots'],
  ['1F9B0','red hair','hair red'],
  ['1F9B1','curly hair','hair curly'],
  ['1F48B','kiss mark','kiss lips'],
  ['1F484','lipstick','lipstick beauty'],
  ['1F489','syringe','syringe injection vaccine'],
  ['1F48A','pill','pill medicine'],
  ['1F6BD','toilet','toilet bathroom'],
  ['1F6BF','shower','shower bath'],
  ['1F6C1','bathtub','bath tub'],
  ['1F9F9','broom','broom sweep'],
  ['1F9FA','basket','basket'],
  ['1F9FB','roll of paper','toilet paper'],
  ['1F9FC','soap','soap clean'],
  ['1F9FD','sponge','sponge clean'],
  ['1F9EF','fire extinguisher','fire safety'],
  ['1F6D2','shopping cart','cart shopping'],
  // Symbols
  ['2705','check mark button','check done yes ok'],
  ['274C','cross mark','x no wrong error'],
  ['2757','exclamation mark','exclamation alert'],
  ['2753','question mark','question help'],
  ['1F4A5','collision','boom explosion'],
  ['1F4AB','dizzy','dizzy star'],
  ['1F4AC','speech bubble','talk speech'],
  ['1F4AD','thought balloon','think thought'],
  ['1F6AB','prohibited','no forbidden ban'],
  ['1F514','bell','bell notification'],
  ['1F515','bell with slash','no bell silence'],
  ['1F4F3','vibration mode','vibrate silent'],
  ['1F4F4','mobile phone off','phone off'],
  ['1F6A9','triangular flag','flag checkpoint'],
  ['1F3F3','white flag','flag white peace'],
  ['1F3F4','black flag','flag black'],
  ['1F3F5','rosette','flower award'],
  ['1F3F7','label','tag price'],
  ['1F4F0','newspaper','news paper'],
  ['1F5DE','rolled-up newspaper','news paper'],
  ['1F4E2','loudspeaker','speaker announcement'],
  ['1F4E3','megaphone','megaphone shout'],
  ['1F4E1','satellite antenna','satellite signal'],
  ['1F4F7','camera','camera photo'],
  ['1F4F8','camera with flash','camera flash photo'],
  ['1F4F9','video camera','video camera record'],
  ['1F4FA','television','tv television'],
  ['1F4FB','radio','radio music'],
  ['1F4FC','videocassette','vhs tape'],
  ['1F4FD','film projector','movie film'],
  ['1F4FE','portable stereo','stereo music boombox'],
  ['1F50E','right-pointing magnifying glass','search find zoom'],
  ['1F50F','lock with ink pen','lock password'],
  ['1F510','locked with key','lock key secure'],
  ['1F511','key','key lock'],
  ['1F512','locked','lock secure'],
  ['1F513','unlocked','unlock open'],
  ['2764','heart','love heart'],
  ['1F4CC','pushpin','pin'],
  ['1F4CE','paperclip','clip attach'],
  ['2702','scissors','cut'],
];

// Build lookup maps
const BY_NAME = new Map();
const BY_KEYWORD = new Map();
const BY_CODE = new Map();

for (const [cp, name, kw] of EMOJI_DATA) {
  const char = String.fromCodePoint(parseInt(cp, 16));
  BY_NAME.set(name.toLowerCase(), { char, name, cp });
  BY_CODE.set(cp.toLowerCase(), { char, name, cp });
  for (const word of kw.split(' ')) {
    if (!BY_KEYWORD.has(word)) BY_KEYWORD.set(word, []);
    BY_KEYWORD.get(word).push({ char, name, cp });
  }
}

function formatEntry(e) {
  return `${e.char}  ${e.name}  (U+${e.cp})`;
}

export default {
  tag: 'emoji',
  instruction: `EMOJI SKILL: Look up emoji by name, keyword, or Unicode codepoint. Emit <emoji>query</emoji>.

Examples:
- "Find emoji for thumbs up" → <emoji>thumbs up</emoji>
- "What is U+1F602?" → <emoji>1F602</emoji>
- "Emoji for fire" → <emoji>fire</emoji>`,
  call(content) {
    const q = content.trim().toLowerCase().replace(/^u\+/i, '');

    // Exact codepoint
    if (/^[0-9a-f]{4,6}$/i.test(q)) {
      const e = BY_CODE.get(q.toUpperCase()) ?? BY_CODE.get(q);
      if (e) return formatEntry(e);
      return `No emoji found for codepoint U+${q.toUpperCase()}`;
    }

    // Exact name
    if (BY_NAME.has(q)) return formatEntry(BY_NAME.get(q));

    // Keyword search
    const words = q.split(/\s+/);
    const candidates = new Map();
    for (const word of words) {
      for (const e of (BY_KEYWORD.get(word) ?? [])) {
        const key = e.cp;
        candidates.set(key, (candidates.get(key) ?? { entry: e, hits: 0 }));
        candidates.get(key).hits++;
      }
    }

    // Also search name contains
    for (const [name, e] of BY_NAME) {
      if (name.includes(q) && !candidates.has(e.cp)) {
        candidates.set(e.cp, { entry: e, hits: 0.5 });
      }
    }

    const sorted = [...candidates.values()].sort((a, b) => b.hits - a.hits).slice(0, 8);
    if (!sorted.length) return `No emoji found for "${content}".`;
    return sorted.map(c => formatEntry(c.entry)).join('\n');
  },
  async handle() {},
};
