const ELEMENTS = [
  null,
  {sym:'H', name:'Hydrogen',    w:1.008,   per:1, grp:1,   state:'gas',     disc:1766, fact:'Most abundant element in the universe.'},
  {sym:'He',name:'Helium',      w:4.003,   per:1, grp:18,  state:'gas',     disc:1868, fact:'Second most abundant element; used in balloons and MRI machines.'},
  {sym:'Li',name:'Lithium',     w:6.941,   per:2, grp:1,   state:'solid',   disc:1817, fact:'Lightest metal; used in rechargeable batteries.'},
  {sym:'Be',name:'Beryllium',   w:9.012,   per:2, grp:2,   state:'solid',   disc:1798, fact:'Used in aerospace alloys; highly toxic dust.'},
  {sym:'B', name:'Boron',       w:10.81,   per:2, grp:13,  state:'solid',   disc:1808, fact:'Used in fiberglass and borax; essential plant micronutrient.'},
  {sym:'C', name:'Carbon',      w:12.011,  per:2, grp:14,  state:'solid',   disc:'ancient', fact:'Basis of all organic chemistry; forms diamond and graphite.'},
  {sym:'N', name:'Nitrogen',    w:14.007,  per:2, grp:15,  state:'gas',     disc:1772, fact:'78% of Earth\'s atmosphere.'},
  {sym:'O', name:'Oxygen',      w:15.999,  per:2, grp:16,  state:'gas',     disc:1774, fact:'Essential for respiration; second most abundant in atmosphere.'},
  {sym:'F', name:'Fluorine',    w:18.998,  per:2, grp:17,  state:'gas',     disc:1886, fact:'Most electronegative element; used in toothpaste (fluoride).'},
  {sym:'Ne',name:'Neon',        w:20.180,  per:2, grp:18,  state:'gas',     disc:1898, fact:'Noble gas; glows orange-red in discharge tubes.'},
  {sym:'Na',name:'Sodium',      w:22.990,  per:3, grp:1,   state:'solid',   disc:1807, fact:'Essential electrolyte; reacts violently with water.'},
  {sym:'Mg',name:'Magnesium',   w:24.305,  per:3, grp:2,   state:'solid',   disc:1755, fact:'Burns with brilliant white flame; used in alloys and fireworks.'},
  {sym:'Al',name:'Aluminum',    w:26.982,  per:3, grp:13,  state:'solid',   disc:1825, fact:'Most abundant metal in Earth\'s crust; used in aircraft.'},
  {sym:'Si',name:'Silicon',     w:28.086,  per:3, grp:14,  state:'solid',   disc:1824, fact:'Basis of modern electronics and computer chips.'},
  {sym:'P', name:'Phosphorus',  w:30.974,  per:3, grp:15,  state:'solid',   disc:1669, fact:'Essential for DNA, ATP, and bones; white phosphorus is extremely toxic.'},
  {sym:'S', name:'Sulfur',      w:32.06,   per:3, grp:16,  state:'solid',   disc:'ancient', fact:'Smells like rotten eggs (as H₂S); used in vulcanizing rubber.'},
  {sym:'Cl',name:'Chlorine',    w:35.45,   per:3, grp:17,  state:'gas',     disc:1774, fact:'Used in water purification; yellow-green toxic gas.'},
  {sym:'Ar',name:'Argon',       w:39.948,  per:3, grp:18,  state:'gas',     disc:1894, fact:'Third most abundant gas in atmosphere; used in light bulbs.'},
  {sym:'K', name:'Potassium',   w:39.098,  per:4, grp:1,   state:'solid',   disc:1807, fact:'Essential electrolyte; symbol K from Latin kalium.'},
  {sym:'Ca',name:'Calcium',     w:40.078,  per:4, grp:2,   state:'solid',   disc:1808, fact:'Most abundant mineral in the human body (bones/teeth).'},
  {sym:'Sc',name:'Scandium',    w:44.956,  per:4, grp:3,   state:'solid',   disc:1879, fact:'Rare earth-like element; used in high-intensity lighting.'},
  {sym:'Ti',name:'Titanium',    w:47.867,  per:4, grp:4,   state:'solid',   disc:1791, fact:'As strong as steel but 40% lighter; highly corrosion-resistant.'},
  {sym:'V', name:'Vanadium',    w:50.942,  per:4, grp:5,   state:'solid',   disc:1801, fact:'Used in steel alloys; vanadium redox batteries for grid storage.'},
  {sym:'Cr',name:'Chromium',    w:51.996,  per:4, grp:6,   state:'solid',   disc:1798, fact:'Makes stainless steel; Cr(VI) compounds are carcinogenic.'},
  {sym:'Mn',name:'Manganese',   w:54.938,  per:4, grp:7,   state:'solid',   disc:1774, fact:'Essential trace element; used in steel production.'},
  {sym:'Fe',name:'Iron',        w:55.845,  per:4, grp:8,   state:'solid',   disc:'ancient', fact:'Most abundant element by mass on Earth; core of magnetism and industry.'},
  {sym:'Co',name:'Cobalt',      w:58.933,  per:4, grp:9,   state:'solid',   disc:1735, fact:'Used in lithium-ion batteries and blue pigments.'},
  {sym:'Ni',name:'Nickel',      w:58.693,  per:4, grp:10,  state:'solid',   disc:1751, fact:'Used in coins and stainless steel; common contact allergen.'},
  {sym:'Cu',name:'Copper',      w:63.546,  per:4, grp:11,  state:'solid',   disc:'ancient', fact:'First metal used by humans; excellent conductor; turns green (patina).'},
  {sym:'Zn',name:'Zinc',        w:65.38,   per:4, grp:12,  state:'solid',   disc:1746, fact:'Used in galvanizing iron; essential for immune function.'},
  {sym:'Ga',name:'Gallium',     w:69.723,  per:4, grp:13,  state:'solid',   disc:1875, fact:'Melts in your hand (29.8°C); used in semiconductors (GaAs).'},
  {sym:'Ge',name:'Germanium',   w:72.630,  per:4, grp:14,  state:'solid',   disc:1886, fact:'Semiconductor; predicted by Mendeleev as "eka-silicon".'},
  {sym:'As',name:'Arsenic',     w:74.922,  per:4, grp:15,  state:'solid',   disc:'ancient', fact:'Famous poison; also a semiconductor dopant.'},
  {sym:'Se',name:'Selenium',    w:78.971,  per:4, grp:16,  state:'solid',   disc:1817, fact:'Used in photovoltaics; essential trace nutrient.'},
  {sym:'Br',name:'Bromine',     w:79.904,  per:4, grp:17,  state:'liquid',  disc:1826, fact:'One of only two liquid elements at room temperature; red-brown, toxic.'},
  {sym:'Kr',name:'Krypton',     w:83.798,  per:4, grp:18,  state:'gas',     disc:1898, fact:'Noble gas; "kryptonite" derives its name from this element.'},
  {sym:'Rb',name:'Rubidium',    w:85.468,  per:5, grp:1,   state:'solid',   disc:1861, fact:'Soft metal that spontaneously ignites in air.'},
  {sym:'Sr',name:'Strontium',   w:87.62,   per:5, grp:2,   state:'solid',   disc:1790, fact:'Sr-90 is a dangerous fission product; strontium gives red color to fireworks.'},
  {sym:'Y', name:'Yttrium',     w:88.906,  per:5, grp:3,   state:'solid',   disc:1794, fact:'Named after Ytterby, Sweden; used in LEDs and superconductors.'},
  {sym:'Zr',name:'Zirconium',   w:91.224,  per:5, grp:4,   state:'solid',   disc:1789, fact:'Used in nuclear reactor cladding; gem cubic zirconia is ZrO₂.'},
  {sym:'Nb',name:'Niobium',     w:92.906,  per:5, grp:5,   state:'solid',   disc:1801, fact:'Used in superconducting magnets and high-strength steels.'},
  {sym:'Mo',name:'Molybdenum',  w:95.95,   per:5, grp:6,   state:'solid',   disc:1778, fact:'Highest melting point of common metals (2623°C); essential enzyme cofactor.'},
  {sym:'Tc',name:'Technetium',  w:98,      per:5, grp:7,   state:'solid',   disc:1937, fact:'First artificially produced element; Tc-99m is the most used medical isotope.'},
  {sym:'Ru',name:'Ruthenium',   w:101.07,  per:5, grp:8,   state:'solid',   disc:1844, fact:'Platinum group metal; used in hard disk coatings.'},
  {sym:'Rh',name:'Rhodium',     w:102.906, per:5, grp:9,   state:'solid',   disc:1803, fact:'Most expensive common metal; used in catalytic converters.'},
  {sym:'Pd',name:'Palladium',   w:106.42,  per:5, grp:10,  state:'solid',   disc:1803, fact:'Used in catalytic converters and hydrogen purification.'},
  {sym:'Ag',name:'Silver',      w:107.868, per:5, grp:11,  state:'solid',   disc:'ancient', fact:'Best electrical conductor of all elements; antimicrobial.'},
  {sym:'Cd',name:'Cadmium',     w:112.414, per:5, grp:12,  state:'solid',   disc:1817, fact:'Toxic heavy metal; used in NiCd batteries and yellow pigments.'},
  {sym:'In',name:'Indium',      w:114.818, per:5, grp:13,  state:'solid',   disc:1863, fact:'Used in ITO for touchscreens and LCD displays.'},
  {sym:'Sn',name:'Tin',         w:118.710, per:5, grp:14,  state:'solid',   disc:'ancient', fact:'Used in bronze (with copper); "tin cans" are actually steel with tin coating.'},
  {sym:'Sb',name:'Antimony',    w:121.760, per:5, grp:15,  state:'solid',   disc:'ancient', fact:'Used in flame retardants; ancient cosmetic (kohl).'},
  {sym:'Te',name:'Tellurium',   w:127.60,  per:5, grp:16,  state:'solid',   disc:1782, fact:'Rarest stable element in Earth\'s crust; used in CdTe solar cells.'},
  {sym:'I', name:'Iodine',      w:126.904, per:5, grp:17,  state:'solid',   disc:1811, fact:'Essential for thyroid hormones; used as antiseptic.'},
  {sym:'Xe',name:'Xenon',       w:131.293, per:5, grp:18,  state:'gas',     disc:1898, fact:'Used in flash lamps, ion thrusters, and anesthesia.'},
  {sym:'Cs',name:'Cesium',      w:132.905, per:6, grp:1,   state:'solid',   disc:1860, fact:'Used in atomic clocks (defining the SI second).'},
  {sym:'Ba',name:'Barium',      w:137.327, per:6, grp:2,   state:'solid',   disc:1808, fact:'Used in barium meals for X-ray imaging of the digestive tract.'},
  {sym:'La',name:'Lanthanum',   w:138.905, per:6, grp:null,state:'solid',   disc:1839, fact:'Lanthanide series; used in camera lenses and hydrogen storage.'},
  {sym:'Ce',name:'Cerium',      w:140.116, per:6, grp:null,state:'solid',   disc:1803, fact:'Most abundant rare-earth element; used in catalytic converters.'},
  {sym:'Pr',name:'Praseodymium',w:140.908, per:6, grp:null,state:'solid',   disc:1885, fact:'Used in high-power permanent magnets.'},
  {sym:'Nd',name:'Neodymium',   w:144.242, per:6, grp:null,state:'solid',   disc:1885, fact:'Makes the strongest permanent magnets (Nd₂Fe₁₄B).'},
  {sym:'Pm',name:'Promethium',  w:145,     per:6, grp:null,state:'solid',   disc:1945, fact:'No stable isotopes; used in some spacecraft RTGs.'},
  {sym:'Sm',name:'Samarium',    w:150.36,  per:6, grp:null,state:'solid',   disc:1879, fact:'Sm-Co magnets work at high temperatures.'},
  {sym:'Eu',name:'Europium',    w:151.964, per:6, grp:null,state:'solid',   disc:1901, fact:'Used in red/blue phosphors in fluorescent lamps and euro banknote security.'},
  {sym:'Gd',name:'Gadolinium',  w:157.25,  per:6, grp:null,state:'solid',   disc:1880, fact:'MRI contrast agent; highest neutron absorption of any element.'},
  {sym:'Tb',name:'Terbium',     w:158.925, per:6, grp:null,state:'solid',   disc:1843, fact:'Used in green phosphors and solid-state drives (Terfenol-D).'},
  {sym:'Dy',name:'Dysprosium',  w:162.500, per:6, grp:null,state:'solid',   disc:1886, fact:'Critical for neodymium magnets in wind turbines and EVs.'},
  {sym:'Ho',name:'Holmium',     w:164.930, per:6, grp:null,state:'solid',   disc:1878, fact:'Highest magnetic moment of any element; used in magnetic pole pieces.'},
  {sym:'Er',name:'Erbium',      w:167.259, per:6, grp:null,state:'solid',   disc:1843, fact:'Used in fiber-optic amplifiers (EDFA).'},
  {sym:'Tm',name:'Thulium',     w:168.934, per:6, grp:null,state:'solid',   disc:1879, fact:'Rarest of the lanthanides; used in portable X-ray units.'},
  {sym:'Yb',name:'Ytterbium',   w:173.045, per:6, grp:null,state:'solid',   disc:1878, fact:'Used in atomic clocks and optical fibers.'},
  {sym:'Lu',name:'Lutetium',    w:174.967, per:6, grp:null,state:'solid',   disc:1907, fact:'Densest and hardest lanthanide; used in PET scanner detectors.'},
  {sym:'Hf',name:'Hafnium',     w:178.486, per:6, grp:4,   state:'solid',   disc:1923, fact:'Used in nuclear reactor control rods; always found with zirconium.'},
  {sym:'Ta',name:'Tantalum',    w:180.948, per:6, grp:5,   state:'solid',   disc:1802, fact:'Used in capacitors for phones and laptops; biocompatible for implants.'},
  {sym:'W', name:'Tungsten',    w:183.84,  per:6, grp:6,   state:'solid',   disc:1783, fact:'Highest melting point of all elements (3422°C); used in light bulb filaments.'},
  {sym:'Re',name:'Rhenium',     w:186.207, per:6, grp:7,   state:'solid',   disc:1925, fact:'Second highest melting point; used in jet engine superalloys.'},
  {sym:'Os',name:'Osmium',      w:190.23,  per:6, grp:8,   state:'solid',   disc:1803, fact:'Densest naturally occurring element (22.59 g/cm³).'},
  {sym:'Ir',name:'Iridium',     w:192.217, per:6, grp:9,   state:'solid',   disc:1803, fact:'Second densest element; the iridium anomaly marks the K-Pg extinction event.'},
  {sym:'Pt',name:'Platinum',    w:195.084, per:6, grp:10,  state:'solid',   disc:1735, fact:'Used in catalytic converters, jewelry, and chemotherapy drugs.'},
  {sym:'Au',name:'Gold',        w:196.967, per:6, grp:11,  state:'solid',   disc:'ancient', fact:'Non-reactive; used as monetary standard throughout history.'},
  {sym:'Hg',name:'Mercury',     w:200.592, per:6, grp:12,  state:'liquid',  disc:'ancient', fact:'Only metal liquid at room temperature; used in thermometers (historically).'},
  {sym:'Tl',name:'Thallium',    w:204.38,  per:6, grp:13,  state:'solid',   disc:1861, fact:'Highly toxic; historically used as rat poison.'},
  {sym:'Pb',name:'Lead',        w:207.2,   per:6, grp:14,  state:'solid',   disc:'ancient', fact:'Heavy, toxic metal; used in shielding, batteries, and historically in pipes/paint.'},
  {sym:'Bi',name:'Bismuth',     w:208.980, per:6, grp:15,  state:'solid',   disc:1753, fact:'Heaviest non-radioactive element; used in low-melting alloys and Pepto-Bismol.'},
  {sym:'Po',name:'Polonium',    w:209,     per:6, grp:16,  state:'solid',   disc:1898, fact:'Discovered by Marie Curie; highly radioactive; used in nuclear devices.'},
  {sym:'At',name:'Astatine',    w:210,     per:6, grp:17,  state:'solid',   disc:1940, fact:'Rarest naturally occurring element on Earth (only ~25g at any time).'},
  {sym:'Rn',name:'Radon',       w:222,     per:6, grp:18,  state:'gas',     disc:1900, fact:'Radioactive noble gas; second leading cause of lung cancer.'},
  {sym:'Fr',name:'Francium',    w:223,     per:7, grp:1,   state:'solid',   disc:1939, fact:'Most unstable naturally occurring element; highly radioactive.'},
  {sym:'Ra',name:'Radium',      w:226,     per:7, grp:2,   state:'solid',   disc:1898, fact:'Discovered by Marie and Pierre Curie; used in early cancer treatment.'},
  {sym:'Ac',name:'Actinium',    w:227,     per:7, grp:null,state:'solid',   disc:1899, fact:'First actinide; intensely radioactive (glows blue in the dark).'},
  {sym:'Th',name:'Thorium',     w:232.038, per:7, grp:null,state:'solid',   disc:1829, fact:'Potential nuclear fuel; thorium cycle produces much less waste than uranium.'},
  {sym:'Pa',name:'Protactinium',w:231.036, per:7, grp:null,state:'solid',   disc:1913, fact:'Extremely toxic and radioactive; found in trace amounts in uranium ores.'},
  {sym:'U', name:'Uranium',     w:238.029, per:7, grp:null,state:'solid',   disc:1789, fact:'Fuel for nuclear power; two naturally occurring fissile isotopes.'},
  {sym:'Np',name:'Neptunium',   w:237,     per:7, grp:null,state:'solid',   disc:1940, fact:'First transuranic element; named after Neptune.'},
  {sym:'Pu',name:'Plutonium',   w:244,     per:7, grp:null,state:'solid',   disc:1940, fact:'Used in nuclear weapons and fuel; Pu-238 powers many space probes.'},
  {sym:'Am',name:'Americium',   w:243,     per:7, grp:null,state:'solid',   disc:1944, fact:'Found in household smoke detectors (Am-241).'},
  {sym:'Cm',name:'Curium',      w:247,     per:7, grp:null,state:'solid',   disc:1944, fact:'Named after Marie and Pierre Curie.'},
  {sym:'Bk',name:'Berkelium',   w:247,     per:7, grp:null,state:'solid',   disc:1949, fact:'Named after Berkeley, California; only made in nanogram quantities.'},
  {sym:'Cf',name:'Californium', w:251,     per:7, grp:null,state:'solid',   disc:1950, fact:'Used as a neutron source in nuclear reactor startup rods.'},
  {sym:'Es',name:'Einsteinium', w:252,     per:7, grp:null,state:'solid',   disc:1952, fact:'Named after Einstein; discovered in fallout from first hydrogen bomb test.'},
  {sym:'Fm',name:'Fermium',     w:257,     per:7, grp:null,state:'solid',   disc:1952, fact:'Named after Fermi; heaviest element made by neutron bombardment.'},
  {sym:'Md',name:'Mendelevium', w:258,     per:7, grp:null,state:'solid',   disc:1955, fact:'Named after Mendeleev; made one atom at a time.'},
  {sym:'No',name:'Nobelium',    w:259,     per:7, grp:null,state:'solid',   disc:1966, fact:'Named after Alfred Nobel; most stable isotope has 58-minute half-life.'},
  {sym:'Lr',name:'Lawrencium',  w:266,     per:7, grp:null,state:'solid',   disc:1961, fact:'Named after Ernest Lawrence; last actinide.'},
  {sym:'Rf',name:'Rutherfordium',w:267,    per:7, grp:4,   state:'solid',   disc:1969, fact:'Named after Ernest Rutherford; extremely short half-life.'},
  {sym:'Db',name:'Dubnium',     w:268,     per:7, grp:5,   state:'solid',   disc:1970, fact:'Named after Dubna, Russia.'},
  {sym:'Sg',name:'Seaborgium',  w:271,     per:7, grp:6,   state:'solid',   disc:1974, fact:'Named after Glenn Seaborg while he was still alive.'},
  {sym:'Bh',name:'Bohrium',     w:272,     per:7, grp:7,   state:'solid',   disc:1981, fact:'Named after Niels Bohr.'},
  {sym:'Hs',name:'Hassium',     w:270,     per:7, grp:8,   state:'solid',   disc:1984, fact:'Named after Hesse, Germany.'},
  {sym:'Mt',name:'Meitnerium',  w:278,     per:7, grp:9,   state:'solid',   disc:1982, fact:'Named after Lise Meitner, co-discoverer of nuclear fission.'},
  {sym:'Ds',name:'Darmstadtium',w:281,     per:7, grp:10,  state:'solid',   disc:1994, fact:'Named after Darmstadt, Germany.'},
  {sym:'Rg',name:'Roentgenium', w:282,     per:7, grp:11,  state:'solid',   disc:1994, fact:'Named after Wilhelm Röntgen, discoverer of X-rays.'},
  {sym:'Cn',name:'Copernicium', w:285,     per:7, grp:12,  state:'gas?',    disc:1996, fact:'Named after Copernicus; may be a gas at room temperature.'},
  {sym:'Nh',name:'Nihonium',    w:286,     per:7, grp:13,  state:'solid',   disc:2004, fact:'Named after Japan (Nihon); first element discovered in Asia.'},
  {sym:'Fl',name:'Flerovium',   w:289,     per:7, grp:14,  state:'solid?',  disc:1998, fact:'Named after Flerov Laboratory of Nuclear Reactions.'},
  {sym:'Mc',name:'Moscovium',   w:290,     per:7, grp:15,  state:'solid',   disc:2003, fact:'Named after Moscow Oblast.'},
  {sym:'Lv',name:'Livermorium', w:293,     per:7, grp:16,  state:'solid',   disc:2000, fact:'Named after Lawrence Livermore National Laboratory.'},
  {sym:'Ts',name:'Tennessine',  w:294,     per:7, grp:17,  state:'solid',   disc:2010, fact:'Named after Tennessee; second heaviest halogen.'},
  {sym:'Og',name:'Oganesson',   w:294,     per:7, grp:18,  state:'solid?',  disc:2002, fact:'Heaviest known element; named after Yuri Oganessian, still living.'},
];

const BY_SYM  = Object.fromEntries(ELEMENTS.filter(Boolean).map((e,i) => [e.sym.toUpperCase(), i+1]));
const BY_NAME = Object.fromEntries(ELEMENTS.filter(Boolean).map((e,i) => [e.name.toUpperCase(), i+1]));

export default {
  tag: 'element',
  instruction: `PERIODIC TABLE SKILL: To look up an element by name, symbol, or atomic number, call <|tool_call>call:element{input:<|"|>value<|"|>}<tool_call|>.

Examples:
- "Tell me about gold" → <|tool_call>call:element{input:<|"|>gold<|"|>}<tool_call|>
- "What is element 79?" → <|tool_call>call:element{input:<|"|>79<|"|>}<tool_call|>
- "Info on Fe" → <|tool_call>call:element{input:<|"|>Fe<|"|>}<tool_call|>`,
  call(content) {
    content = content.trim();
    const n = parseInt(content);
    let idx = !isNaN(n) ? n : BY_SYM[content.toUpperCase()] ?? BY_NAME[content.toUpperCase()];
    const e = ELEMENTS[idx];
    if (!e) return `Element not found: "${content}". Try a symbol (Au), name (Gold), or number (79).`;
    return [
      `${e.sym} — ${e.name} (Z=${idx})`,
      `Atomic weight: ${e.w}`,
      `Period: ${e.per}  Group: ${e.grp ?? 'lanthanide/actinide'}`,
      `State at STP: ${e.state}`,
      `Discovered: ${e.disc}`,
      `Fun fact: ${e.fact}`,
    ].join('\n');
  },
  async handle() {},
};
