const ROOTS = {
  // Greek
  'photo':  {lang:'Greek',meaning:'light',examples:'photograph, photon, photosynthesis'},
  'graph':  {lang:'Greek',meaning:'write/draw',examples:'photograph, biography, autograph'},
  'bio':    {lang:'Greek',meaning:'life',examples:'biology, biography, biopsy'},
  'logos':  {lang:'Greek',meaning:'word/study/reason',examples:'biology, theology, logic'},
  'geo':    {lang:'Greek',meaning:'earth',examples:'geology, geography, geometry'},
  'hydro':  {lang:'Greek',meaning:'water',examples:'hydrogen, hydrology, dehydrate'},
  'chron':  {lang:'Greek',meaning:'time',examples:'chronology, synchronize, anachronism'},
  'tele':   {lang:'Greek',meaning:'far/distant',examples:'telephone, telescope, television'},
  'therm':  {lang:'Greek',meaning:'heat',examples:'thermometer, thermal, hypothermia'},
  'phon':   {lang:'Greek',meaning:'sound/voice',examples:'telephone, microphone, phonics'},
  'astro':  {lang:'Greek',meaning:'star',examples:'astronomy, astronaut, astrology'},
  'phil':   {lang:'Greek',meaning:'love',examples:'philosophy, Philadelphia, bibliophile'},
  'sophi':  {lang:'Greek',meaning:'wisdom',examples:'philosophy, sophist, sophisticated'},
  'demo':   {lang:'Greek',meaning:'people',examples:'democracy, demographic, epidemic'},
  'krat':   {lang:'Greek',meaning:'rule/power',examples:'democracy, aristocracy, bureaucracy'},
  'auto':   {lang:'Greek',meaning:'self',examples:'autobiography, automobile, autopilot'},
  'micro':  {lang:'Greek',meaning:'small',examples:'microscope, microbe, microwave'},
  'macro':  {lang:'Greek',meaning:'large',examples:'macroeconomics, macroscopic'},
  'mono':   {lang:'Greek',meaning:'one/single',examples:'monologue, monopoly, monotone'},
  'poly':   {lang:'Greek',meaning:'many',examples:'polygon, polyglot, polynomial'},
  'anti':   {lang:'Greek',meaning:'against/opposite',examples:'antidote, antibody, antisocial'},
  'hyper':  {lang:'Greek',meaning:'over/excessive',examples:'hyperactive, hyperbole, hypertension'},
  'hypo':   {lang:'Greek',meaning:'under/deficient',examples:'hypothesis, hypocrite, hypoglycemia'},
  'para':   {lang:'Greek',meaning:'beside/beyond',examples:'parallel, parasite, paranormal'},
  'peri':   {lang:'Greek',meaning:'around',examples:'perimeter, peripheral, periscope'},
  'syn':    {lang:'Greek',meaning:'together/with',examples:'synonym, synthesis, synchronize'},
  'anti':   {lang:'Greek',meaning:'against',examples:'antibiotic, antiseptic, antonym'},
  'pseudo': {lang:'Greek',meaning:'false',examples:'pseudonym, pseudoscience'},
  'eu':     {lang:'Greek',meaning:'good/well',examples:'euphoria, euthanasia, eulogy'},
  'dys':    {lang:'Greek',meaning:'bad/difficult',examples:'dyslexia, dysfunctional, dystopia'},
  'meta':   {lang:'Greek',meaning:'beyond/after/change',examples:'metaphor, metabolism, metamorphosis'},
  'neo':    {lang:'Greek',meaning:'new',examples:'neologism, neonatal, Neo-classical'},
  'path':   {lang:'Greek',meaning:'feeling/disease/suffering',examples:'sympathy, pathology, empathy'},
  'morph':  {lang:'Greek',meaning:'form/shape',examples:'morphology, metamorphosis, amorphous'},
  'crat':   {lang:'Greek',meaning:'rule',examples:'democracy, bureaucracy, aristocracy'},
  'arch':   {lang:'Greek',meaning:'chief/rule',examples:'archbishop, monarchy, archive'},
  'trop':   {lang:'Greek',meaning:'turn/change',examples:'tropism, heliotrope, atrophy'},
  'scope':  {lang:'Greek',meaning:'look/see',examples:'telescope, microscope, horoscope'},
  'meter':  {lang:'Greek',meaning:'measure',examples:'thermometer, barometer, speedometer'},
  // Latin
  'aqua':   {lang:'Latin',meaning:'water',examples:'aquatic, aquarium, aqueduct'},
  'dict':   {lang:'Latin',meaning:'say/speak',examples:'dictionary, dictate, predict'},
  'duc':    {lang:'Latin',meaning:'lead/guide',examples:'conduct, deduce, educate, introduce'},
  'fact':   {lang:'Latin',meaning:'make/do',examples:'factory, artifact, manufacture'},
  'fac':    {lang:'Latin',meaning:'make/do',examples:'faculty, facilitate, benefactor'},
  'port':   {lang:'Latin',meaning:'carry',examples:'transport, portable, export, support'},
  'rupt':   {lang:'Latin',meaning:'break',examples:'interrupt, corrupt, erupt, disrupt'},
  'scrib':  {lang:'Latin',meaning:'write',examples:'describe, prescribe, scribble'},
  'script': {lang:'Latin',meaning:'write',examples:'scripture, manuscript, inscription'},
  'spec':   {lang:'Latin',meaning:'see/look',examples:'spectacle, inspect, spectacular'},
  'spect':  {lang:'Latin',meaning:'see/look',examples:'spectator, suspect, retrospect'},
  'aud':    {lang:'Latin',meaning:'hear',examples:'audio, auditorium, audible'},
  'vid':    {lang:'Latin',meaning:'see',examples:'video, evident, provide'},
  'vis':    {lang:'Latin',meaning:'see',examples:'vision, visible, revise'},
  'voc':    {lang:'Latin',meaning:'voice/call',examples:'vocabulary, invoke, vocal'},
  'loc':    {lang:'Latin',meaning:'place',examples:'location, relocate, locomotive'},
  'luc':    {lang:'Latin',meaning:'light',examples:'lucid, illuminate, translucent'},
  'man':    {lang:'Latin',meaning:'hand',examples:'manual, manufacture, manuscript'},
  'mot':    {lang:'Latin',meaning:'move',examples:'motor, motion, emotion, promote'},
  'nov':    {lang:'Latin',meaning:'new',examples:'novel, innovate, renovate'},
  'omni':   {lang:'Latin',meaning:'all',examples:'omnipotent, omnivore, omniscient'},
  'ped':    {lang:'Latin',meaning:'foot',examples:'pedestrian, pedal, expedition'},
  'sent':   {lang:'Latin',meaning:'feel/sense',examples:'sentiment, sensation, consent'},
  'struct':  {lang:'Latin',meaning:'build',examples:'structure, construct, destruction'},
  'terr':   {lang:'Latin',meaning:'land/earth',examples:'territory, terrain, terrestrial'},
  'trans':  {lang:'Latin',meaning:'across/beyond',examples:'transport, transform, translate'},
  'ver':    {lang:'Latin',meaning:'truth',examples:'verify, verdict, verity'},
  'vit':    {lang:'Latin',meaning:'life',examples:'vital, vitamin, vitality'},
  'mort':   {lang:'Latin',meaning:'death',examples:'mortal, immortal, mortgage'},
  'cred':   {lang:'Latin',meaning:'believe',examples:'credit, credible, credence'},
  'bene':   {lang:'Latin',meaning:'good/well',examples:'beneficial, benefit, benevolent'},
  'mal':    {lang:'Latin',meaning:'bad/evil',examples:'malicious, malfunction, malevolent'},
  'multi':  {lang:'Latin',meaning:'many',examples:'multiply, multitude, multimedia'},
  'inter':  {lang:'Latin',meaning:'between/among',examples:'international, interrupt, interact'},
  'intra':  {lang:'Latin',meaning:'within',examples:'intranet, intramural, intravenous'},
  'extra':  {lang:'Latin',meaning:'outside/beyond',examples:'extraordinary, extraterrestrial'},
  'super':  {lang:'Latin',meaning:'above/over',examples:'superior, supervise, supernatural'},
  'sub':    {lang:'Latin',meaning:'under/below',examples:'submarine, subtract, subway'},
  'pre':    {lang:'Latin',meaning:'before',examples:'predict, preview, precede'},
  'post':   {lang:'Latin',meaning:'after',examples:'postpone, postmortem, postscript'},
  're':     {lang:'Latin',meaning:'again/back',examples:'repeat, return, revise, rebuild'},
  'ex':     {lang:'Latin',meaning:'out of/from',examples:'export, extract, exclude, exhale'},
  'ad':     {lang:'Latin',meaning:'to/toward',examples:'adapt, advance, adhere, adjoin'},
  'con':    {lang:'Latin',meaning:'together/with',examples:'connect, construct, consolidate'},
  'de':     {lang:'Latin',meaning:'down/away from',examples:'decrease, defrost, demolish'},
  'dis':    {lang:'Latin',meaning:'not/apart',examples:'disagree, disappear, displace'},
  'in':     {lang:'Latin',meaning:'not/into',examples:'invisible, include, insist'},
  'un':     {lang:'Latin',meaning:'not/reverse',examples:'unhappy, undo, unknown'},
  'mis':    {lang:'Latin',meaning:'wrong/bad',examples:'misplace, misunderstand, mistake'},
  'fort':   {lang:'Latin',meaning:'strong',examples:'fortify, effort, comfort'},
  'grat':   {lang:'Latin',meaning:'thankful/pleasing',examples:'grateful, gratitude, congratulate'},
};

export default {
  tag: 'root',
  instruction: `WORD ROOTS SKILL: To look up the origin and meaning of a Latin or Greek root, emit <root>root</root>.

Examples:
- "What does 'photo' mean?" → <root>photo</root>
- "Root meaning of 'graph'" → <root>graph</root>
- "Latin root 'port'" → <root>port</root>`,
  call(content) {
    const key = content.trim().toLowerCase();
    const r   = ROOTS[key];
    if (!r) return `Root "${key}" not found. The table covers common Latin and Greek roots.`;
    return [`${key} (${r.lang}): "${r.meaning}"`,`Examples: ${r.examples}`].join('\n');
  },
  async handle() {},
};
