// Top ~200 airports: IATA code → city, full name
const AIRPORTS = {
  ATL:{city:'Atlanta, GA',name:'Hartsfield–Jackson Atlanta International'},
  LAX:{city:'Los Angeles, CA',name:'Los Angeles International'},
  ORD:{city:'Chicago, IL',name:"O'Hare International"},
  DFW:{city:'Dallas/Fort Worth, TX',name:'Dallas/Fort Worth International'},
  DEN:{city:'Denver, CO',name:'Denver International'},
  JFK:{city:'New York, NY',name:'John F. Kennedy International'},
  SFO:{city:'San Francisco, CA',name:'San Francisco International'},
  SEA:{city:'Seattle, WA',name:'Seattle–Tacoma International'},
  LAS:{city:'Las Vegas, NV',name:'Harry Reid International'},
  MCO:{city:'Orlando, FL',name:'Orlando International'},
  EWR:{city:'Newark, NJ',name:'Newark Liberty International'},
  MIA:{city:'Miami, FL',name:'Miami International'},
  CLT:{city:'Charlotte, NC',name:'Charlotte Douglas International'},
  MSP:{city:'Minneapolis, MN',name:'Minneapolis–Saint Paul International'},
  BOS:{city:'Boston, MA',name:'Logan International'},
  PHL:{city:'Philadelphia, PA',name:'Philadelphia International'},
  LGA:{city:'New York, NY',name:'LaGuardia'},
  IAH:{city:'Houston, TX',name:'George Bush Intercontinental'},
  PHX:{city:'Phoenix, AZ',name:'Phoenix Sky Harbor International'},
  DTW:{city:'Detroit, MI',name:'Detroit Metropolitan Wayne County'},
  FLL:{city:'Fort Lauderdale, FL',name:'Fort Lauderdale–Hollywood International'},
  BWI:{city:'Baltimore, MD',name:'Baltimore/Washington International'},
  SLC:{city:'Salt Lake City, UT',name:'Salt Lake City International'},
  SAN:{city:'San Diego, CA',name:'San Diego International'},
  MDW:{city:'Chicago, IL',name:'Chicago Midway International'},
  BNA:{city:'Nashville, TN',name:'Nashville International'},
  IAD:{city:'Washington DC',name:'Dulles International'},
  DCA:{city:'Washington DC',name:'Reagan National'},
  MSY:{city:'New Orleans, LA',name:'Louis Armstrong New Orleans International'},
  AUS:{city:'Austin, TX',name:'Austin–Bergstrom International'},
  HNL:{city:'Honolulu, HI',name:'Daniel K. Inouye International'},
  PDX:{city:'Portland, OR',name:'Portland International'},
  STL:{city:'St. Louis, MO',name:'St. Louis Lambert International'},
  MCI:{city:'Kansas City, MO',name:'Kansas City International'},
  OAK:{city:'Oakland, CA',name:'Oakland Metropolitan International'},
  SJC:{city:'San Jose, CA',name:'Norman Y. Mineta San José International'},
  RDU:{city:'Raleigh, NC',name:'Raleigh–Durham International'},
  SMF:{city:'Sacramento, CA',name:'Sacramento International'},
  RSW:{city:'Fort Myers, FL',name:'Southwest Florida International'},
  BDL:{city:'Hartford, CT',name:'Bradley International'},
  TPA:{city:'Tampa, FL',name:'Tampa International'},
  PIT:{city:'Pittsburgh, PA',name:'Pittsburgh International'},
  CLE:{city:'Cleveland, OH',name:'Cleveland Hopkins International'},
  CMH:{city:'Columbus, OH',name:'John Glenn Columbus International'},
  IND:{city:'Indianapolis, IN',name:'Indianapolis International'},
  SNA:{city:'Orange County, CA',name:'John Wayne Airport'},
  MKE:{city:'Milwaukee, WI',name:'Milwaukee Mitchell International'},
  OGG:{city:'Maui, HI',name:'Kahului Airport'},
  ABQ:{city:'Albuquerque, NM',name:'Albuquerque International Sunport'},
  BUR:{city:'Burbank, CA',name:'Hollywood Burbank Airport'},
  LHR:{city:'London, UK',name:'Heathrow'},
  LGW:{city:'London, UK',name:'Gatwick'},
  LCY:{city:'London, UK',name:'City Airport'},
  STN:{city:'London, UK',name:'Stansted'},
  LTN:{city:'London, UK',name:'Luton'},
  MAN:{city:'Manchester, UK',name:'Manchester Airport'},
  EDI:{city:'Edinburgh, UK',name:'Edinburgh Airport'},
  GLA:{city:'Glasgow, UK',name:'Glasgow International'},
  CDG:{city:'Paris, France',name:'Charles de Gaulle'},
  ORY:{city:'Paris, France',name:'Orly'},
  AMS:{city:'Amsterdam, Netherlands',name:'Amsterdam Airport Schiphol'},
  FRA:{city:'Frankfurt, Germany',name:'Frankfurt Airport'},
  MUC:{city:'Munich, Germany',name:'Franz Josef Strauss International'},
  TXL:{city:'Berlin, Germany',name:'Tegel (closed 2020)'},
  BER:{city:'Berlin, Germany',name:'Berlin Brandenburg'},
  ZRH:{city:'Zurich, Switzerland',name:'Zurich Airport'},
  GVA:{city:'Geneva, Switzerland',name:'Geneva Airport'},
  VIE:{city:'Vienna, Austria',name:'Vienna International'},
  BRU:{city:'Brussels, Belgium',name:'Brussels Airport'},
  CPH:{city:'Copenhagen, Denmark',name:'Copenhagen Airport'},
  ARN:{city:'Stockholm, Sweden',name:'Stockholm Arlanda'},
  OSL:{city:'Oslo, Norway',name:'Oslo Gardermoen'},
  HEL:{city:'Helsinki, Finland',name:'Helsinki–Vantaa'},
  MAD:{city:'Madrid, Spain',name:'Adolfo Suárez Madrid–Barajas'},
  BCN:{city:'Barcelona, Spain',name:'Josep Tarradellas Barcelona–El Prat'},
  FCO:{city:'Rome, Italy',name:'Leonardo da Vinci–Fiumicino'},
  LIN:{city:'Milan, Italy',name:'Milan Linate'},
  MXP:{city:'Milan, Italy',name:'Malpensa International'},
  ATH:{city:'Athens, Greece',name:'Athens International (Eleftherios Venizelos)'},
  WAW:{city:'Warsaw, Poland',name:'Chopin Airport'},
  PRG:{city:'Prague, Czech Republic',name:'Václav Havel Airport Prague'},
  BUD:{city:'Budapest, Hungary',name:'Budapest Liszt Ferenc International'},
  OTP:{city:'Bucharest, Romania',name:'Henri Coandă International'},
  LIS:{city:'Lisbon, Portugal',name:'Humberto Delgado Airport'},
  OPO:{city:'Porto, Portugal',name:'Francisco Sá Carneiro Airport'},
  DUB:{city:'Dublin, Ireland',name:'Dublin Airport'},
  HEL:{city:'Helsinki, Finland',name:'Helsinki–Vantaa'},
  LED:{city:'St. Petersburg, Russia',name:'Pulkovo Airport'},
  SVO:{city:'Moscow, Russia',name:'Sheremetyevo International'},
  DME:{city:'Moscow, Russia',name:'Domodedovo International'},
  IST:{city:'Istanbul, Turkey',name:'Istanbul Airport'},
  SAW:{city:'Istanbul, Turkey',name:'Sabiha Gökçen International'},
  TLV:{city:'Tel Aviv, Israel',name:'Ben Gurion International'},
  CAI:{city:'Cairo, Egypt',name:'Cairo International'},
  DXB:{city:'Dubai, UAE',name:'Dubai International'},
  AUH:{city:'Abu Dhabi, UAE',name:'Zayed International'},
  DOH:{city:'Doha, Qatar',name:'Hamad International'},
  RUH:{city:'Riyadh, Saudi Arabia',name:'King Khalid International'},
  JED:{city:'Jeddah, Saudi Arabia',name:'King Abdulaziz International'},
  KWI:{city:'Kuwait City, Kuwait',name:'Kuwait International'},
  AMM:{city:'Amman, Jordan',name:'Queen Alia International'},
  BEY:{city:'Beirut, Lebanon',name:'Rafic Hariri International'},
  THR:{city:'Tehran, Iran',name:'Imam Khomeini International'},
  KHI:{city:'Karachi, Pakistan',name:'Jinnah International'},
  ISB:{city:'Islamabad, Pakistan',name:'New Islamabad International'},
  LHE:{city:'Lahore, Pakistan',name:'Allama Iqbal International'},
  DEL:{city:'Delhi, India',name:'Indira Gandhi International'},
  BOM:{city:'Mumbai, India',name:'Chhatrapati Shivaji Maharaj International'},
  BLR:{city:'Bengaluru, India',name:'Kempegowda International'},
  MAA:{city:'Chennai, India',name:'Chennai International'},
  CCU:{city:'Kolkata, India',name:'Netaji Subhas Chandra Bose International'},
  HYD:{city:'Hyderabad, India',name:'Rajiv Gandhi International'},
  DAC:{city:'Dhaka, Bangladesh',name:'Hazrat Shahjalal International'},
  CMB:{city:'Colombo, Sri Lanka',name:'Bandaranaike International'},
  KTM:{city:'Kathmandu, Nepal',name:'Tribhuvan International'},
  BKK:{city:'Bangkok, Thailand',name:'Suvarnabhumi'},
  DMK:{city:'Bangkok, Thailand',name:'Don Mueang International'},
  HAN:{city:'Hanoi, Vietnam',name:'Nội Bài International'},
  SGN:{city:'Ho Chi Minh City, Vietnam',name:'Tân Sơn Nhất International'},
  SIN:{city:'Singapore',name:'Changi Airport'},
  KUL:{city:'Kuala Lumpur, Malaysia',name:'Kuala Lumpur International'},
  CGK:{city:'Jakarta, Indonesia',name:'Soekarno–Hatta International'},
  MNL:{city:'Manila, Philippines',name:'Ninoy Aquino International'},
  MFM:{city:'Macau',name:'Macau International'},
  HKG:{city:'Hong Kong',name:'Hong Kong International'},
  PEK:{city:'Beijing, China',name:'Capital International'},
  PKX:{city:'Beijing, China',name:'Daxing International'},
  PVG:{city:'Shanghai, China',name:'Pudong International'},
  SHA:{city:'Shanghai, China',name:'Hongqiao International'},
  CAN:{city:'Guangzhou, China',name:'Baiyun International'},
  SZX:{city:'Shenzhen, China',name:'Bao\'an International'},
  CTU:{city:'Chengdu, China',name:'Tianfu International'},
  TPE:{city:'Taipei, Taiwan',name:'Taiwan Taoyuan International'},
  TSA:{city:'Taipei, Taiwan',name:'Songshan Airport'},
  ICN:{city:'Seoul, South Korea',name:'Incheon International'},
  GMP:{city:'Seoul, South Korea',name:'Gimpo International'},
  NRT:{city:'Tokyo, Japan',name:'Narita International'},
  HND:{city:'Tokyo, Japan',name:'Haneda Airport'},
  KIX:{city:'Osaka, Japan',name:'Kansai International'},
  ITM:{city:'Osaka, Japan',name:'Osaka Itami Airport'},
  SYD:{city:'Sydney, Australia',name:'Kingsford Smith'},
  MEL:{city:'Melbourne, Australia',name:'Melbourne Airport (Tullamarine)'},
  BNE:{city:'Brisbane, Australia',name:'Brisbane Airport'},
  PER:{city:'Perth, Australia',name:'Perth Airport'},
  ADL:{city:'Adelaide, Australia',name:'Adelaide Airport'},
  AKL:{city:'Auckland, New Zealand',name:'Auckland Airport'},
  CHC:{city:'Christchurch, New Zealand',name:'Christchurch Airport'},
  WLG:{city:'Wellington, New Zealand',name:'Wellington Airport'},
  YYZ:{city:'Toronto, Canada',name:'Toronto Pearson International'},
  YUL:{city:'Montreal, Canada',name:'Montréal–Trudeau International'},
  YVR:{city:'Vancouver, Canada',name:'Vancouver International'},
  YYC:{city:'Calgary, Canada',name:'Calgary International'},
  YEG:{city:'Edmonton, Canada',name:'Edmonton International'},
  YOW:{city:'Ottawa, Canada',name:'Ottawa Macdonald–Cartier International'},
  MEX:{city:'Mexico City, Mexico',name:'Benito Juárez International'},
  GDL:{city:'Guadalajara, Mexico',name:'Miguel Hidalgo y Costilla International'},
  MTY:{city:'Monterrey, Mexico',name:'General Mariano Escobedo International'},
  CUN:{city:'Cancún, Mexico',name:'Cancún International'},
  BOG:{city:'Bogotá, Colombia',name:'El Dorado International'},
  MDE:{city:'Medellín, Colombia',name:'José María Córdova International'},
  GRU:{city:'São Paulo, Brazil',name:'Guarulhos International'},
  CGH:{city:'São Paulo, Brazil',name:'Congonhas Airport'},
  GIG:{city:'Rio de Janeiro, Brazil',name:'Galeão International'},
  SDU:{city:'Rio de Janeiro, Brazil',name:'Santos Dumont Airport'},
  BSB:{city:'Brasília, Brazil',name:'Presidente Juscelino Kubitschek International'},
  EZE:{city:'Buenos Aires, Argentina',name:'Ministro Pistarini International (Ezeiza)'},
  AEP:{city:'Buenos Aires, Argentina',name:'Jorge Newbery Airport'},
  SCL:{city:'Santiago, Chile',name:'Arturo Merino Benítez International'},
  LIM:{city:'Lima, Peru',name:'Jorge Chávez International'},
  UIO:{city:'Quito, Ecuador',name:'Mariscal Sucre International'},
  JNB:{city:'Johannesburg, South Africa',name:'O. R. Tambo International'},
  CPT:{city:'Cape Town, South Africa',name:'Cape Town International'},
  NBO:{city:'Nairobi, Kenya',name:'Jomo Kenyatta International'},
  ADD:{city:'Addis Ababa, Ethiopia',name:'Bole International'},
  LOS:{city:'Lagos, Nigeria',name:'Murtala Muhammed International'},
  CMN:{city:'Casablanca, Morocco',name:'Mohammed V International'},
  ALG:{city:'Algiers, Algeria',name:'Houari Boumediene Airport'},
  TUN:{city:'Tunis, Tunisia',name:'Tunis Carthage International'},
  DAR:{city:'Dar es Salaam, Tanzania',name:'Julius Nyerere International'},
  ACC:{city:'Accra, Ghana',name:'Kotoka International'},
  ABV:{city:'Abuja, Nigeria',name:'Nnamdi Azikiwe International'},
  HRE:{city:'Harare, Zimbabwe',name:'Robert Gabriel Mugabe International'},
  LFW:{city:'Lomé, Togo',name:'Gnassingbé Eyadéma International'},
};

const BY_CITY = {};
for (const [code, info] of Object.entries(AIRPORTS)) {
  const city = info.city.split(',')[0].toUpperCase();
  BY_CITY[city] = BY_CITY[city] ?? [];
  BY_CITY[city].push(code);
}

export default {
  tag: 'airport',
  instruction: `AIRPORT CODE SKILL: To look up an airport by IATA code or city name, emit <airport>code or city</airport>.

Examples:
- "What is LAX?" → <airport>LAX</airport>
- "Airport in Tokyo" → <airport>Tokyo</airport>`,
  call(content) {
    const input  = content.trim().toUpperCase();
    const direct = AIRPORTS[input];
    if (direct) return `${input}: ${direct.name}\n${direct.city}`;
    const city   = BY_CITY[input];
    if (city) return city.map(c => `${c}: ${AIRPORTS[c].name} — ${AIRPORTS[c].city}`).join('\n');
    return `Not found: "${content}". Try an IATA code (LAX) or city name (London).`;
  },
  async handle() {},
};
